import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="navbar">
                    <Link href="/">홈</Link>
                    <Link href="/list">상품 리스트</Link>
                    <Link href="/cart">장바구니</Link>
                    <Link href="/cart/payment">결제 내역</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
